"""Initial migration

Revision ID: f8c87e7645bb
Revises: 
Create Date: 2024-12-05 08:29:01.336639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c87e7645bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_classes_level'), 'classes', ['level'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_table('courses',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('otherNames', sa.String(), nullable=True),
    sa.Column('dateOfBirth', sa.Date(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('registry',
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.Column('classId', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classId'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('registry_id')
    )
    op.create_index(op.f('ix_registry_status'), 'registry', ['status'], unique=False)
    op.create_table('student_courses',
    sa.Column('student_courses_id', sa.UUID(), nullable=False),
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.Column('courseId', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_courses_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_courses')
    op.drop_index(op.f('ix_registry_status'), table_name='registry')
    op.drop_table('registry')
    op.drop_table('students')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_level'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
